### ISSUE TITLE
Error in running ASCETS Error in `left_join()`: ! `...` must be empty. ✖ Problematic argument: • relationship = "many-to-many"

### ISSUE THREAD

**Issue by maximus3219** [beroukhim-lab/ascets#10]
I just follow the instruction on your main page and use the example data, but it just fails to run with 
Error in `left_join()`:
! `...` must be empty.
✖ Problematic argument:
• relationship = "many-to-many"

In details:
`
cna <- read.delim("G:/Sarcoma/ascets-1.1.3/sample_data/input/seg_example.seg")
cytoband <- read.delim ("G:/Sarcoma/ascets-1.1.3/genomic_arm_coordinates_hg19.txt")
noise <- read.delim("G:/Sarcoma/ascets-1.1.3/sample_data/input/lcr_example.txt")

ascets_output <- ascets(cna, 
                        cytoband, 
                        min_boc = 0.5, 
                        name = unique(cna$sample), 
                        noise,
                        keep_noisy = FALSE, 
                        threshold = 0.2, alteration_threshold = 0.7)

<error/rlib_error_dots_nonempty>
Error in `left_join()`:
! `...` must be empty.
✖ Problematic argument:
• relationship = "many-to-many"
---
Backtrace:
     ▆
  1. ├─global ascets(...)
  2. │ └─global annotate_cytobands(cna, cytoband) at Sarcoma/ascets-1.1.3/ascets_resources.R:336:2
  3. │   ├─... %>% distinct() at Sarcoma/ascets-1.1.3/ascets_resources.R:231:2
  4. │   ├─dplyr::left_join(cna, cytoband, by = "chrom", relationship = "many-to-many")
  5. │   └─dplyr:::left_join.data.frame(cna, cytoband, by = "chrom", relationship = "many-to-many")
  6. │     └─rlang::check_dots_empty0(...)
  7. │       └─rlang::check_dots_empty(call = call)
  8. │         └─rlang:::action_dots(...)
  9. │           ├─base (local) try_dots(...)
 10. │           └─rlang (local) action(...)
 11. ├─dplyr::distinct(.)
 12. ├─dplyr::mutate(...)
 13. ├─dplyr::filter(...)
 14. └─dplyr::ungroup(.)

<html>
<body>

sessionInfo() R version 4.2.2 (2022-10-31 ucrt) Platform: x86_64-w64-mingw32/x64 (64-bit) Running under: Windows 10 x64 (build 19045)  Matrix products: default  locale: [1] LC_COLLATE=Chinese (Traditional)_Hong Kong SAR.utf8  LC_CTYPE=Chinese (Traditional)_Hong Kong SAR.utf8    [3] LC_MONETARY=Chinese (Traditional)_Hong Kong SAR.utf8 LC_NUMERIC=C                                         [5] LC_TIME=Chinese (Traditional)_Hong Kong SAR.utf8      attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       other attached packages:  [1] data.table_1.14.8 lubridate_1.9.3   forcats_1.0.0     stringr_1.5.0     dplyr_1.1.0       purrr_1.0.1       readr_2.1.4       tidyr_1.3.0        [9] tibble_3.1.8      ggplot2_3.4.2     tidyverse_2.0.0    loaded via a namespace (and not attached):   [1] colorspace_2.1-0            rjson_0.2.21                siggenes_1.72.0             mclust_6.0.0                DNAcopy_1.72.3                [6] XVector_0.38.0              GenomicRanges_1.50.2        base64_2.0.1                rstudioapi_0.14             bit64_4.0.5                  [11] AnnotationDbi_1.60.2        fansi_1.0.4                 xml2_1.3.3                  R.methodsS3_1.8.2           codetools_0.2-18             [16] splines_4.2.2               sparseMatrixStats_1.10.0    cachem_1.0.7                scrime_1.3.5                maftools_2.14.0              [21] Rsamtools_2.14.0            annotate_1.76.0             dbplyr_2.3.2                R.oo_1.25.0                 png_0.1-8                    [26] pheatmap_1.0.12             HDF5Array_1.26.0            compiler_4.2.2              httr_1.4.6                  Matrix_1.6-4                 [31] fastmap_1.1.1               limma_3.54.2                cli_3.6.0                   prettyunits_1.1.1           tools_4.2.2                  [36] gtable_0.3.3                glue_1.6.2                  GenomeInfoDbData_1.2.9      rappdirs_0.3.3              doRNG_1.8.6                  [41] Rcpp_1.0.10                 Biobase_2.58.0              bumphunter_1.40.0           vctrs_0.5.2                 Biostrings_2.66.0            [46] rhdf5filters_1.10.0         multtest_2.54.0             preprocessCore_1.60.2       nlme_3.1-160                rtracklayer_1.58.0           [51] iterators_1.0.14            DelayedMatrixStats_1.20.0   timechange_0.2.0            lifecycle_1.0.3             restfulr_0.0.15              [56] rngtools_1.5.2              XML_3.99-0.13               beanplot_1.3.1              scales_1.2.1                zlibbioc_1.44.0              [61] MASS_7.3-58.1               hms_1.1.3                   MatrixGenerics_1.10.0       parallel_4.2.2              SummarizedExperiment_1.28.0  [66] minfi_1.43.1                rhdf5_2.42.0                GEOquery_2.66.0             RColorBrewer_1.1-3          yaml_2.3.7                   [71] curl_5.0.0                  memoise_2.0.1               biomaRt_2.54.1              reshape_0.8.9               stringi_1.7.12               [76] RSQLite_2.3.0               genefilter_1.80.3           S4Vectors_0.36.2            BiocIO_1.8.0                foreach_1.5.2                [81] GenomicFeatures_1.50.4      BiocGenerics_0.44.0         filelock_1.0.2              BiocParallel_1.32.5         GenomeInfoDb_1.34.9          [86] rlang_1.1.1                 pkgconfig_2.0.3             matrixStats_0.63.0          bitops_1.0-7                nor1mix_1.3-0                [91] lattice_0.20-45             Rhdf5lib_1.20.0             GenomicAlignments_1.34.0    bit_4.0.5                   tidyselect_1.2.0             [96] plyr_1.8.8                  magrittr_2.0.3              R6_2.5.1                    IRanges_2.32.0              generics_0.1.3              [101] DelayedArray_0.23.2         DBI_1.1.3                   withr_2.5.0                 pillar_1.9.0                survival_3.4-0              [106] KEGGREST_1.38.0             RCurl_1.98-1.10             crayon_1.5.2                utf8_1.2.3                  BiocFileCache_2.6.1         [111] tzdb_0.3.0                  progress_1.2.2              locfit_1.5-9.7              grid_4.2.2                  blob_1.2.4                  [116] digest_0.6.31               xtable_1.8-4                R.utils_2.12.2              illuminaio_0.40.0           munsell_0.5.0               [121] openssl_2.0.5               stats4_4.2.2                askpass_1.1                 quadprog_1.5-8
--
 
> | >
>

</body>
</html>
`

Seems there is some problem of ASCET itself?
An solutions for the problem? Thanks

**Comment by lfspurr** [comment]
Hi - sorry for the delay, for some reason I didn't get an email notification about this issue. I haven't run into this issue myself. I just tried running the latest version on the GENIE data via R studio, and it worked OK on my end. The most common reasons for issues like this are 1) having other packages which override functions from the required packages (I would recommend rerunning with only the necessary packages loaded) and 2) having duplicate entries for the same sample name (ex. having 2 overlapping copy number segments).

Feel free to reach out via email if you want me to try running it with your data (I imagine you may not want to post it publicly): liam.spurr@gmail.com
