### ISSUE TITLE
Using FACETS copy number caller results as input.

### ISSUE THREAD

**Issue by paularstrpo** [beroukhim-lab/ascets#2]
Hi. I am looking at using this tool to get some arm-level copy number calls. Currently I'm using the [MSK facets](https://github.com/mskcc/facets) tool for CNV-calling. FACETS does not strictly use circular binary segmentation, but rather an extension of it, bivariate genome segmentation (described in the facets vignette and below):

```
A bivariate genome segmentation is performed on logR and logOR by extending the CBS algorithm to the bivariate scenario using a T^2 statistic for identifying change points. If the maximal statistic is greater than a pre-determined critical value (cval), we declare a change exists and the change points that maximize this statistic. Lower cval lead to higher sensitivity for small changes. After segmentation, a clustering process is applied to group the segments into clusters of the same underlying genotype.
``` 

I wanted to double check whether segmentation results generated from this method are compatible with the ASCETS statistical methodology. Thanks!

**Comment by lfspurr** [comment]
Yes, I’ve used it on FACETS segmentation files and it works well. I have not tested using the L2CR values for threshold estimation, but if you choose to use the point estimates as opposed to a default or manual threshold for amplification/deletion (-t argument), you can review the segment mean histogram to verify the threshold approximates the width of the central peak in the histogram.
