### ISSUE TITLE
where can i find RobustCNV?

### ISSUE THREAD

**Issue by jeongmeani** [beroukhim-lab/ascets#3]
HI,

to use ASCETS, i want to follow your pipeline.
but i couldn't find RobustCNV anywhere

would you give me a link to install RobustCNV?

Jeongmin

**Comment by lfspurr** [comment]
Unfortunately, RobustCNV is a proprietary algorithm used by Dana-Farber internal genomic pipelines (see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5505210/). However, other widely available copy number calling/segmentation algorithms work well. For example, I have used files from FACETS, CNVkit and GATK4, which all are compatible with ASCETS.

It is likely other algorithms will work too, but I have not tested them. If you choose to use the LCRs (as opposed to default or manual thresholds) from other copy number estimation algorithms for identification of the AMP/DEL threshold, it would be prudent to review the segment mean histogram to verify the threshold identified from the LCRs approximates the width of the central peak. For example, in my experience, LCRs from CNVkit produce threshold estimates that are too conservative as the segmentation algorithm often creates segments that span large regions of sparse coverage. This creates a high level of noise in these segments, and as a result the distribution of noise values across samples do not fit the assumption that the noise values follow an approximately Gaussian distribution. For this reason, I choose a manual threshold for CNVkit files. Verifying this for whichever algorithm you choose will help to ensure accurate aSCNA calls.
