### ISSUE TITLE
The seg file issue

### ISSUE THREAD

**Issue by honghh2018** [beroukhim-lab/ascets#4]
Hi developer,
     There was a question about the seg file, where the *.seg file generated?
what software can generated this file?
I had below excel file, it  can turn into seg format file whether or not?
![image](https://user-images.githubusercontent.com/41668708/156699579-de3e0f96-40be-4b9f-b9a4-47d6a91b37d0.png)

Any advice would be appreciated
Best,
hanhuihong

**Comment by lfspurr** [comment]
Hi Hanhuihong,

I'm not sure I recognize that file type—a number of algorithms can produce .seg files, including GATK4, and FACETS, among others. In essence, these .seg files represent denoised copy number estimates where genomic regions with similar copy number states are combined into one "segment". These algorithms mostly implement circular binary segmentation to accomplish this. You can read more about CBS here: https://bioconductor.org/packages/release/bioc/vignettes/DNAcopy/inst/doc/DNAcopy.pdf

Best wishes,
Liam
