### ISSUE TITLE
The seg file issue

### ISSUE THREAD

**Issue by honghh2018** [beroukhim-lab/ascets#5]
Hi developer,
     I get a seg file like below picture, however, the example seg file had different column, especially the last column.
The example last column was log2ratio, my data was seg_mean. so how can i change the segment mean into log2ratio and then using the ascets software?
PS: my seg file generated by GISTIC software
![image](https://user-images.githubusercontent.com/41668708/159427806-1d6bc3b0-8ea3-45ce-bb37-3e0ba6fbcadf.png)

Had any advices for this issue?
Best,
hanhuihong

**Comment by lfspurr** [comment]
Those are log2ratios and you can use that seg file as is.

Liam
