### ISSUE TITLE
Use it for whole exome sequencing?

### ISSUE THREAD

**Issue by xiasijian** [beroukhim-lab/ascets#6]
Thanks for your excellent software, do it use for whole exome sequencing?

**Comment by lfspurr** [comment]
Yes, it can absolutely be used for exome (or whole genome) sequencing. You may consider making the threshold for calling aSCNAs (-t argument) less stringent (-0.1/0.1) given the lower level of noise in WES as opposed to targeted sequencing, but the optimal threshold is likely dependent on the specific dataset.
