### ISSUE TITLE
Aneuploidy score for polyploid genomes

### ISSUE THREAD

**Issue by andreyurch** [beroukhim-lab/ascets#8]
Dear developer,

Thank you for this great tool!  I have a question: if I have a genome where the majority of chromosomes are 4n (let's say 20 chromosomes), then aneuploidy score for this genome will be around 0.9? Right? But then, we will not be able to distinguish it from another genome where we have a mix of 4n and 3n chromosomes (50/50% respectively) while the second one will be significantly more unstable. What do you think?

**Comment by lfspurr** [comment]
Hello, thanks for reaching out and for your question.

As the aneuploidy score is calculated from log2 copy ratios, it should be relative to the sample ploidy. So in a diploid sample, a log2 copy ratio of 0 would represent copy number of 2, but the same would be 4 in a genome doubled sample (4n). So a basic approximation would be that in a tetraploid genome, if you had 75% of chromosomes at CN 4 and 25% at CN 3, then the aneuploidy score would be ~0.25. Aneuploidy is defined only as unbalanced chromosome arm number, so an arm having a copy-number of 4 where you have 2 copies of each chromosome is technically not aneuploid. (see paragraph 2 under Results in this paper for further explanation https://www.cell.com/cancer-cell/fulltext/S1535-6108(18)30111-9). 

However, this all relies on the baseline/ploidy being set by the copy number calling algorithm (FACETS, ABSOLUTE, etc). Identifying the average sample ploidy can obviously be tricky as there are often multiple possible solutions. So in your example, a solution identifying the tumor as tetraploid with some 3n chromosomes mixed in is going to have a lower aneuploidy score than if the solution has a baseline to be 3n with many amplified arms to 4n.

Hope this helps!
