### ISSUE TITLE
Error in if (max_alt_type == "NEUTRAL") { : the condition has length > 1

### ISSUE THREAD

**Issue by fcgportal** [beroukhim-lab/ascets#9]
Dear developer,
Thanks for this great tool! I got an error when ran the code. 

Rscript ./run_ascets.R -i gct_msk_2016-data_cna_hg19.txt -c ./genomic_arm_coordinates_hg19.txt -m 0.2  -k F -a 0.7 -o gct_msk_2016

Parsing data...
Determining breadth of coverage...
Cropping segments...
Computing weighted averages...
Computing alteration fractions...
Making arm level calls...
Error in if (max_alt_type == "NEUTRAL") { : the condition has length > 1
Calls: ascets -> make_all_calls -> lapply -> FUN -> lapply -> FUN
Execution halted

The attached is one of the seg files ran into an error. Would you please help? Thanks.
[gct_msk_2016-data_cna_hg19.txt](https://github.com/beroukhim-lab/ascets/files/13992138/gct_msk_2016-data_cna_hg19.txt)

**Comment by lfspurr** [comment]
Hello, thanks for your question! 

I checked your file, and it looks like some of your samples are duplicated but with different log2ratios for the same segment coordinates. A screenshot of one sample is pasted below (gct_msk_2016<P-0003963-T01-IM3). I would recommend taking a look into your file and selecting the correct sample entries, then rerun ASCETS. If you still have issues after trying this, please let me know!

<img width="673" alt="Screenshot 2024-01-22 at 7 34 04 PM" src="https://github.com/beroukhim-lab/ascets/assets/30680009/95383328-4a52-484e-9862-9e8c9aea690b">

**Comment by fcgportal** [comment]
Thank you for your reply. After I cleaned up the seg files, the error still pop out. 
[msk_spectrum_tme_2022-data_cna_hg19.txt](https://github.com/beroukhim-lab/ascets/files/14043352/msk_spectrum_tme_2022-data_cna_hg19.txt)

**Comment by lfspurr** [comment]
Got it. There was a bug where some chromosome arms that were 0% altered in WGS samples would introduce NAs which interfered with making the aSCNA calls. It should be fixed now. I tested with the new file you provided and have pasted the results below. Let me know if it works on your end. Thanks!

<img width="898" alt="Screenshot 2024-01-24 at 2 52 57 PM" src="https://github.com/beroukhim-lab/ascets/assets/30680009/7e9bdd96-ad8e-4282-afa0-ab9354496ba6">

[msk_spectrum_tme_arm_weighted_average_segmeans.txt](https://github.com/beroukhim-lab/ascets/files/14043522/msk_spectrum_tme_arm_weighted_average_segmeans.txt)
[msk_spectrum_tme_arm_level_calls.txt](https://github.com/beroukhim-lab/ascets/files/14043523/msk_spectrum_tme_arm_level_calls.txt)
[msk_spectrum_tme_segmean_hist.pdf](https://github.com/beroukhim-lab/ascets/files/14043524/msk_spectrum_tme_segmean_hist.pdf)
[msk_spectrum_tme_aneuploidy_scores.txt](https://github.com/beroukhim-lab/ascets/files/14043525/msk_spectrum_tme_aneuploidy_scores.txt)
[msk_spectrum_tme_params.txt](https://github.com/beroukhim-lab/ascets/files/14043526/msk_spectrum_tme_params.txt)

**Comment by fcgportal** [comment]
Thank you so much for quick reply! All my seg files work now except this one.
[mbn_mdacc_2013-data_cna_hg19.txt](https://github.com/beroukhim-lab/ascets/files/14044983/mbn_mdacc_2013-data_cna_hg19.txt)

**Comment by lfspurr** [comment]
Should be all set. Very weird edge case where one arm (1q in mbn_mdacc_2013<DLBCL_113) had the exact same number of bases amplified as were neutral. Now accounted for and tested with your file—it should run properly.
